package com.ims.config;

import com.ims.shared.auth.TenantContext;
import lombok.extern.slf4j.Slf4j;
import org.hibernate.resource.jdbc.spi.StatementInspector;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

/**
 * HARD TEST COMPONENT: TenantLeakInterceptor.
 * Intercepts every SQL statement generated by Hibernate.
 * In 'test' profile, it ensures that any query hitting a multi-tenant table
 * MUST contain a 'tenant_id' filter.
 */
@Profile("test")
@Slf4j
@Component
public class TenantLeakInterceptor implements StatementInspector {

  private static final String[] MULTI_TENANT_TABLES = {
      "products", "orders", "order_items", "customers", "suppliers",
      "stock_movements", "invoices", "payments", "categories"
  };

  @Override
  public String inspect(String sql) {
    if (sql == null)
      return null;

    // Skip platform-level tasks (sentinel -1L)
    Long currentTenant = TenantContext.getTenantId();
    if (currentTenant != null && currentTenant.equals(-1L)) {
      return sql;
    }

    String lowerSql = sql.toLowerCase();

    // Only inspect SELECT/UPDATE/DELETE
    if (lowerSql.startsWith("insert")) {
      return sql;
    }

    for (String table : MULTI_TENANT_TABLES) {
      if (lowerSql.matches(".*\\b" + table + "\\b.*")) {
        // Basic check for tenant_id filter.
        if (!lowerSql.contains("tenant_id")) {
          log.error("🛑 TENANT LEAK DETECTED! Table '{}' accessed without tenant_id filter.", table);
          log.error("SQL: {}", sql);
          throw new com.ims.shared.exception.TenantIsolationException(
              "Security Violation: Query hitting multi-tenant table '" + table + "' is missing a tenant_id filter!");
        }
      }
    }

    return sql;
  }
}
