spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ims_db
    username: ims_user
    password: changeme
  data:
    redis:
      host: localhost
      port: 6379
      password: changeme
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    listener:
      auto-startup: false

app:
  jwt:
    secret: ${JWT_SECRET:oEWvO7Zun6LpLSYX4MIZbvtWm/gb+qhlWw6nFKHjD5nxb3pwOIyNI0s5eVsSWFGRR5Ntr+o2hymLug4zuYYp4g}
  security:
    allowed-origins: "http://localhost:5173"
  rate-limit:
    enabled: false

  redis:
    enabled: true