app:
  jwt:
    secret: "1kA2LI4GBW8Goua0gdEsWSyAT4OH+npD172GmO8lisg="
    expiry-seconds: 86400
    refresh-expiry-seconds: 604800
  security:
    allowed-origins: "http://localhost:3000,http://localhost:5173"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ims_db
    username: ims_user
    password: D0JWxAxXR73r4qe5AQJVDP4R0lKCRqZf
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  cache:
    type: redis