apiVersion: v1
kind: Secret
metadata:
  name: ims-secrets
  namespace: ims-namespace
type: Opaque
stringData:
  DB_URL: "jdbc:postgresql://postgres-service:5432/ims_db"
  DB_USER: "ims_user"
  DB_PASSWORD: "change-me"
  REDIS_HOST: "redis-service"
  REDIS_PASSWORD: "change-me"
  JWT_SECRET: "replace-with-a-very-long-and-secure-random-string"
  APP_ENCRYPTION_KEY: "01234567890123456789012345678901"
