apiVersion: v1
kind: Service
metadata:
  name: ims-service
  namespace: ims-namespace
spec:
  selector:
    app: ims-backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
