apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: inventry-backend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: inventry-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ims-postgres-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ims-postgres
