-- V45__add_missing_updated_at_columns.sql
ALTER TABLE categories
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE suppliers
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE support_tickets
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();
ALTER TABLE subscription_plans
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT NOW();