-- ============================================
-- V53__create_webhook_outbox.sql
-- Implementing Transactional Outbox pattern for reliable webhook delivery
-- ============================================

CREATE TABLE IF NOT EXISTS webhook_outbox (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    webhook_id BIGINT,
    event_type VARCHAR(100) NOT NULL,
    payload TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING', -- PENDING, PROCESSING, COMPLETED, FAILED
    retry_count INTEGER DEFAULT 0,
    next_retry_at TIMESTAMP,
    last_error TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    processed_at TIMESTAMP
);

CREATE INDEX idx_webhook_outbox_status_retry ON webhook_outbox(status, next_retry_at) 
WHERE status IN ('PENDING', 'FAILED');

CREATE INDEX idx_webhook_outbox_tenant ON webhook_outbox(tenant_id);
