-- ============================================
-- V56__create_api_keys.sql
-- Adding support for scoped API Keys for third-party integrations
-- ============================================

CREATE TABLE IF NOT EXISTS api_keys (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    key_hash VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    scopes TEXT, -- JSON array of permissions
    is_active BOOLEAN DEFAULT TRUE,
    expires_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP
);

CREATE INDEX idx_api_keys_tenant ON api_keys(tenant_id);
CREATE INDEX idx_api_keys_hash ON api_keys(key_hash);
