-- ============================================
-- V62__create_outbox_events.sql
-- Creating the generic outbox_events table
-- ============================================

CREATE TABLE outbox_events (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tenant_id BIGINT NOT NULL,
    aggregate_type VARCHAR(255) NOT NULL,
    aggregate_id VARCHAR(255) NOT NULL,
    event_type VARCHAR(255) NOT NULL,
    payload TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    attempts INTEGER NOT NULL DEFAULT 0,
    is_processed BOOLEAN NOT NULL DEFAULT FALSE,
    last_error TEXT
);

CREATE INDEX idx_outbox_events_tenant_processed ON outbox_events(tenant_id, is_processed) 
WHERE is_processed = FALSE;

CREATE INDEX idx_outbox_events_created_at ON outbox_events(created_at);
